title: Introvertebrates
description: Exploring the biology, behaviour, and care of invertebrates through video, writing, and digital tools.
url: "https://introvertebrates.com"
markdown: kramdown

collections:
  research:
    output: true
    permalink: /research/:name/
  kryp_weekly:
    output: true
    permalink: /kryp/ukas-dyr/:name/

defaults:
  - scope:
      path: ""
      type: research
    values:
      layout: research_article
  - scope:
      path: ""
      type: kryp_weekly
    values:
      layout: kryp_weekly_article
